# Generated by Django 4.2.2 on 2023-06-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_genre_options_alter_genre_name_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Хэштег', 'verbose_name_plural': 'Хэштеги'},
        ),
    ]
