# Generated by Django 4.2.2 on 2023-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Введите категорию', max_length=200, verbose_name='Категория'),
        ),
    ]
