# Generated by Django 4.2.2 on 2023-06-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_author_articles_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
