# Generated by Django 4.2.2 on 2023-06-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_hull_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hull',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AddField(
            model_name='articles',
            name='Hull',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.hull'),
        ),
        migrations.AddField(
            model_name='articles',
            name='school_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.school'),
        ),
    ]
